language: ruby
rvm:
  - "1.9.3"
  - rbx-19mode
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - 'cd spec/dummy && bundle exec rake worth_saving:install:migrations'
  - 'RAILS_ENV=test bundle exec rake db:migrate'
  - 'cd ../../ && bundle exec rspec spec'
